import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Md. Moniruzzaman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className} > */}
      <body className={`${inter.className} bg-blue-50 relative  `}>
        {/* red circle  */}
        <div className="redCircle absolute -z-[10] top-0 left-[38%] xsm:left-[45%] sm:left-[50%] rounded-full h-[8rem] w-[12rem]  xsm:h-[6.5rem] xsm:w-[14rem]  sm:h-[7rem] sm:w-[16rem] md:h-[9rem] md:w-[18rem] lg:h-[12rem] lg:w-[22rem]  bg-red-500 blur-[17rem] "></div>

        {/* blue circle   */}
        <div className="blueCircle absolute -z-[10] top-0 left-[14%] xsm:left-[18%] sm:left-[28%] rounded-full h-[8rem] w-[12rem]  xsm:h-[6.5rem] xsm:w-[14rem]  sm:h-[7rem] sm:w-[16rem] md:h-[9rem] md:w-[18rem] lg:h-[12rem] lg:w-[22rem]  bg-blue-500 blur-[19rem] "></div>

        {children}
      </body>
    </html>
  );
}
